# Application Deployment (webapp: ConversaoTemperatura)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura
spec:
  selector:
    matchLabels:
      app: conversao-temperatura
  template:
    metadata:
      labels:
        app: conversao-temperatura
    spec:
      containers:
        - name: conversao-temperatura
          image: gm50x/conversao-temperatura:v1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "50m"
              memory: "100M"
            limits:
              cpu: "50m"
              memory: "100M"
---
apiVersion: v1
kind: Service
metadata:
  name: conversao-temperatura
spec:
  selector:
    app: conversao-temperatura
  ports:
    - appProtocol: TCP
      port: 8081
      targetPort: 8080
  type: LoadBalancer
